"""Characterization tests locking glossary behavior byte-for-byte before/after
the precompiled-pattern refactor. Expected values were generated by running the
pre-refactor implementation; do not "fix" them without a deliberate behavior
change.
"""

from book_translate.glossary import (
    Term,
    appearing_terms,
    apply_glossary,
    protect_html,
    protect_text,
    restore_text,
    term_in,
)


TERMS = [
    Term("Sharpe ratio", "夏普比率", ("Sharpe", "sharpe ratios")),
    Term("Transformer", "变换器", ("Transformers",)),
    Term("GAN", "生成对抗网络", ("GANs", "generative adversarial network")),
    Term("DiT", "DiT"),
    Term("attention", "注意力"),
    Term("never-used", "不出现"),
]

ITEMS = [
    "The Sharpe ratio of a GAN differs from sharpe ratios of Transformers.",
    "Attention? No: attention is all you need, says the Transformer paper (GANs disagree).",
    "A generative adversarial network (GAN) uses no DiT blocks.",
]


def test_apply_glossary_exact_outputs():
    protected, maps, hint, appearing = apply_glossary(ITEMS, TERMS)
    # Per item: terms are ordered longest-variant-first, and only the first
    # variant that hits is substituted ("sharpe ratios" wins over "Sharpe
    # ratio" in item 0, leaving "Sharpe ratio" for restore's hard lock).
    assert protected == [
        "The Sharpe ratio of a @@BT0@@ differs from @@BT1@@ of @@BT2@@.",
        "Attention? No: @@BT2@@ is all you need, says the @@BT1@@ paper (@@BT0@@ disagree).",
        "A @@BT0@@ (GAN) uses no @@BT1@@ blocks.",
    ]
    # Placeholder numbering restarts at 0 for every item.
    assert maps == [
        [("@@BT0@@", "生成对抗网络"), ("@@BT1@@", "夏普比率"), ("@@BT2@@", "变换器")],
        [("@@BT0@@", "生成对抗网络"), ("@@BT1@@", "变换器"), ("@@BT2@@", "注意力")],
        [("@@BT0@@", "生成对抗网络"), ("@@BT1@@", "DiT")],
    ]
    assert hint == (
        "【术语表】下列术语必须按给定译法，不得改写：\n"
        "- Sharpe ratio（Sharpe / sharpe ratios） → 夏普比率\n"
        "- Transformer（Transformers） → 变换器\n"
        "- GAN（GANs / generative adversarial network） → 生成对抗网络\n"
        "- DiT → DiT\n"
        "- attention → 注意力\n"
        "原文中的 @@BTn@@ 占位符必须原样保留，不要翻译或改写。"
    )
    assert [t.source for t in appearing] == [
        "Sharpe ratio",
        "Transformer",
        "GAN",
        "DiT",
        "attention",
    ]


def test_restore_text_exact_outputs():
    _protected, maps, _hint, appearing = apply_glossary(ITEMS, TERMS)
    zh = [
        "@@BT0@@与@@BT1@@的差异见@@BT2@@。",
        "注意 @@BT0@@ 就是全部,Transformer 论文如是说;GANs 不同意。",
        "@@BT1@@ 不用 @@BT0@@ 模块。",
    ]
    # Hard lock rewrites leftover source/alias hits ("Transformer", "GANs"),
    # is case-sensitive, and skips variants equal to the target ("DiT").
    assert restore_text(zh[0], maps[0], appearing) == "生成对抗网络与夏普比率的差异见变换器。"
    assert (
        restore_text(zh[1], maps[1], appearing)
        == "注意 生成对抗网络 就是全部,变换器 论文如是说;生成对抗网络 不同意。"
    )
    assert restore_text(zh[2], maps[2], appearing) == "DiT 不用 生成对抗网络 模块。"


def test_protect_text_start_offset_and_ordering():
    protected, mapping = protect_text("Sharpe and GAN together", TERMS, start=7)
    # GAN sorts first (longest alias, 30 chars) so it takes the lower index.
    assert protected == "@@BT8@@ and @@BT7@@ together"
    assert mapping == [("@@BT7@@", "生成对抗网络"), ("@@BT8@@", "夏普比率")]


def test_boundary_semantics_unchanged():
    art = Term("art", "艺术")
    assert term_in("modern art here", art)
    assert not term_in("a fresh start", art)  # alnum boundary blocks mid-word
    plus = Term("C++", "C加加")
    assert term_in("likesC++too", plus)  # non-alnum edge -> no boundary guard
    assert appearing_terms(["", "no hits", "modern art"], [art, plus]) == [art]
    assert appearing_terms([], [art]) == []
    assert appearing_terms(["modern art"], []) == []


def test_appearing_terms_no_false_positive_across_texts():
    # "foo bar" must not match when "foo" and "bar" live in different texts.
    fb = Term("foo bar", "富霸")
    assert appearing_terms(["ends with foo", "bar starts this"], [fb]) == []
    assert appearing_terms(["one foo bar two"], [fb]) == [fb]


def test_protect_html_numbering_spans_nodes():
    html = "<p>GAN one</p><p>GAN two and DiT</p>"
    out, mapping = protect_html(html, [Term("GAN", "生成对抗网络"), Term("DiT", "DiT")])
    assert out == "<p>@@BT0@@ one</p><p>@@BT1@@ two and @@BT2@@</p>"
    assert mapping == [
        ("@@BT0@@", "生成对抗网络"),
        ("@@BT1@@", "生成对抗网络"),
        ("@@BT2@@", "DiT"),
    ]


def _big_terms(n: int) -> list[Term]:
    return [Term(f"Alpha{i:03d}", f"术{i:03d}", (f"alias-{i:03d}",)) for i in range(n)]


def test_over_512_terms_protect_restore_correct():
    # 600 terms x 2 variants = 1200 distinct patterns, well past re's 512-entry
    # compile cache. Results must stay correct (and fast).
    n = 600
    terms = _big_terms(n)
    text = " ".join(f"Alpha{i:03d}" for i in range(n))
    protected, mapping = protect_text(text, terms)
    # All variants share maxlen 9, so the stable sort keeps glossary order.
    assert protected == " ".join(f"@@BT{i}@@" for i in range(n))
    assert mapping == [(f"@@BT{i}@@", f"术{i:03d}") for i in range(n)]
    assert restore_text(protected, mapping, terms) == " ".join(
        f"术{i:03d}" for i in range(n)
    )


def test_over_512_terms_alias_hits_and_hard_lock():
    n = 600
    terms = _big_terms(n)
    text = "alias-042 then Alpha599 then alias-000"
    protected, mapping = protect_text(text, terms)
    assert protected == "@@BT1@@ then @@BT2@@ then @@BT0@@"
    assert mapping == [
        ("@@BT0@@", "术000"),
        ("@@BT1@@", "术042"),
        ("@@BT2@@", "术599"),
    ]
    leftover = restore_text("@@BT1@@ 与 Alpha007 及 @@BT0@@", mapping, terms)
    assert leftover == "术042 与 术007 及 术000"
